// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	sql "entgo.io/ent/dialect/sql"
)

// BasketLine is an autogenerated mock type for the BasketLine type
type BasketLine struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *BasketLine) Execute(_a0 *sql.Selector) {
	_m.Called(_a0)
}
