// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: ShoppingBasket.proto

package ShoppingBasket

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Date int64  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

type CreateEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type GetEventByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetEventByIdRequest) Reset() {
	*x = GetEventByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventByIdRequest) ProtoMessage() {}

func (x *GetEventByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventByIdRequest.ProtoReflect.Descriptor instead.
func (*GetEventByIdRequest) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEventByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *GetEventByIdResponse) Reset() {
	*x = GetEventByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEventByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventByIdResponse) ProtoMessage() {}

func (x *GetEventByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventByIdResponse.ProtoReflect.Descriptor instead.
func (*GetEventByIdResponse) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventByIdResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// Basket
type Basket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketId string `protobuf:"bytes,1,opt,name=basket_id,json=basketId,proto3" json:"basket_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *Basket) Reset() {
	*x = Basket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Basket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Basket) ProtoMessage() {}

func (x *Basket) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Basket.ProtoReflect.Descriptor instead.
func (*Basket) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{5}
}

func (x *Basket) GetBasketId() string {
	if x != nil {
		return x.BasketId
	}
	return ""
}

func (x *Basket) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateBasketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CouponCode string `protobuf:"bytes,2,opt,name=couponCode,proto3" json:"couponCode,omitempty"`
}

func (x *CreateBasketRequest) Reset() {
	*x = CreateBasketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasketRequest) ProtoMessage() {}

func (x *CreateBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasketRequest.ProtoReflect.Descriptor instead.
func (*CreateBasketRequest) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBasketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBasketRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

type CreateBasketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Basket *Basket `protobuf:"bytes,1,opt,name=basket,proto3" json:"basket,omitempty"`
}

func (x *CreateBasketResponse) Reset() {
	*x = CreateBasketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBasketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasketResponse) ProtoMessage() {}

func (x *CreateBasketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasketResponse.ProtoReflect.Descriptor instead.
func (*CreateBasketResponse) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{7}
}

func (x *CreateBasketResponse) GetBasket() *Basket {
	if x != nil {
		return x.Basket
	}
	return nil
}

type GetBasketByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketId string `protobuf:"bytes,1,opt,name=basketId,proto3" json:"basketId,omitempty"`
}

func (x *GetBasketByIdRequest) Reset() {
	*x = GetBasketByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasketByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketByIdRequest) ProtoMessage() {}

func (x *GetBasketByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBasketByIdRequest) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{8}
}

func (x *GetBasketByIdRequest) GetBasketId() string {
	if x != nil {
		return x.BasketId
	}
	return ""
}

type GetBasketByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Basket *Basket `protobuf:"bytes,1,opt,name=basket,proto3" json:"basket,omitempty"`
}

func (x *GetBasketByIdResponse) Reset() {
	*x = GetBasketByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasketByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketByIdResponse) ProtoMessage() {}

func (x *GetBasketByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBasketByIdResponse) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{9}
}

func (x *GetBasketByIdResponse) GetBasket() *Basket {
	if x != nil {
		return x.Basket
	}
	return nil
}

// BasketLine
type BasketLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketLineId string  `protobuf:"bytes,1,opt,name=basket_line_id,json=basketLineId,proto3" json:"basket_line_id,omitempty"`
	TicketAmount uint32  `protobuf:"varint,2,opt,name=ticket_amount,json=ticketAmount,proto3" json:"ticket_amount,omitempty"`
	Price        float32 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	BasketId     string  `protobuf:"bytes,4,opt,name=basket_id,json=basketId,proto3" json:"basket_id,omitempty"`
}

func (x *BasketLine) Reset() {
	*x = BasketLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasketLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketLine) ProtoMessage() {}

func (x *BasketLine) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketLine.ProtoReflect.Descriptor instead.
func (*BasketLine) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{10}
}

func (x *BasketLine) GetBasketLineId() string {
	if x != nil {
		return x.BasketLineId
	}
	return ""
}

func (x *BasketLine) GetTicketAmount() uint32 {
	if x != nil {
		return x.TicketAmount
	}
	return 0
}

func (x *BasketLine) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BasketLine) GetBasketId() string {
	if x != nil {
		return x.BasketId
	}
	return ""
}

type CreateBasketLineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketId     string  `protobuf:"bytes,1,opt,name=basketId,proto3" json:"basketId,omitempty"`
	Price        float32 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	TicketAmount uint32  `protobuf:"varint,3,opt,name=ticket_amount,json=ticketAmount,proto3" json:"ticket_amount,omitempty"`
}

func (x *CreateBasketLineRequest) Reset() {
	*x = CreateBasketLineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBasketLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasketLineRequest) ProtoMessage() {}

func (x *CreateBasketLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasketLineRequest.ProtoReflect.Descriptor instead.
func (*CreateBasketLineRequest) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{11}
}

func (x *CreateBasketLineRequest) GetBasketId() string {
	if x != nil {
		return x.BasketId
	}
	return ""
}

func (x *CreateBasketLineRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateBasketLineRequest) GetTicketAmount() uint32 {
	if x != nil {
		return x.TicketAmount
	}
	return 0
}

type CreateBasketLineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketLine *BasketLine `protobuf:"bytes,1,opt,name=basket_line,json=basketLine,proto3" json:"basket_line,omitempty"`
}

func (x *CreateBasketLineResponse) Reset() {
	*x = CreateBasketLineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBasketLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasketLineResponse) ProtoMessage() {}

func (x *CreateBasketLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasketLineResponse.ProtoReflect.Descriptor instead.
func (*CreateBasketLineResponse) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{12}
}

func (x *CreateBasketLineResponse) GetBasketLine() *BasketLine {
	if x != nil {
		return x.BasketLine
	}
	return nil
}

type GetBasketLineByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketLineId string `protobuf:"bytes,1,opt,name=basketLineId,proto3" json:"basketLineId,omitempty"`
}

func (x *GetBasketLineByIdRequest) Reset() {
	*x = GetBasketLineByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasketLineByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketLineByIdRequest) ProtoMessage() {}

func (x *GetBasketLineByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketLineByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBasketLineByIdRequest) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{13}
}

func (x *GetBasketLineByIdRequest) GetBasketLineId() string {
	if x != nil {
		return x.BasketLineId
	}
	return ""
}

type GetBasketLineByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketLine *BasketLine `protobuf:"bytes,1,opt,name=basket_line,json=basketLine,proto3" json:"basket_line,omitempty"`
}

func (x *GetBasketLineByIdResponse) Reset() {
	*x = GetBasketLineByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasketLineByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketLineByIdResponse) ProtoMessage() {}

func (x *GetBasketLineByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketLineByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBasketLineByIdResponse) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{14}
}

func (x *GetBasketLineByIdResponse) GetBasketLine() *BasketLine {
	if x != nil {
		return x.BasketLine
	}
	return nil
}

type UpdateBasketLineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketLineId string  `protobuf:"bytes,1,opt,name=basketLineId,proto3" json:"basketLineId,omitempty"`
	TicketAmount uint32  `protobuf:"varint,2,opt,name=ticket_amount,json=ticketAmount,proto3" json:"ticket_amount,omitempty"`
	Price        float32 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *UpdateBasketLineRequest) Reset() {
	*x = UpdateBasketLineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBasketLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasketLineRequest) ProtoMessage() {}

func (x *UpdateBasketLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasketLineRequest.ProtoReflect.Descriptor instead.
func (*UpdateBasketLineRequest) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateBasketLineRequest) GetBasketLineId() string {
	if x != nil {
		return x.BasketLineId
	}
	return ""
}

func (x *UpdateBasketLineRequest) GetTicketAmount() uint32 {
	if x != nil {
		return x.TicketAmount
	}
	return 0
}

func (x *UpdateBasketLineRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateBasketLineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketLine *BasketLine `protobuf:"bytes,1,opt,name=basket_line,json=basketLine,proto3" json:"basket_line,omitempty"`
}

func (x *UpdateBasketLineResponse) Reset() {
	*x = UpdateBasketLineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBasketLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasketLineResponse) ProtoMessage() {}

func (x *UpdateBasketLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasketLineResponse.ProtoReflect.Descriptor instead.
func (*UpdateBasketLineResponse) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateBasketLineResponse) GetBasketLine() *BasketLine {
	if x != nil {
		return x.BasketLine
	}
	return nil
}

type DeleteBasketLineByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketLineId string `protobuf:"bytes,1,opt,name=basketLineId,proto3" json:"basketLineId,omitempty"`
}

func (x *DeleteBasketLineByIdRequest) Reset() {
	*x = DeleteBasketLineByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBasketLineByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBasketLineByIdRequest) ProtoMessage() {}

func (x *DeleteBasketLineByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBasketLineByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteBasketLineByIdRequest) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteBasketLineByIdRequest) GetBasketLineId() string {
	if x != nil {
		return x.BasketLineId
	}
	return ""
}

type DeleteBasketLineByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *DeleteBasketLineByIdResponse) Reset() {
	*x = DeleteBasketLineByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBasketLineByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBasketLineByIdResponse) ProtoMessage() {}

func (x *DeleteBasketLineByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBasketLineByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteBasketLineByIdResponse) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteBasketLineByIdResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DeleteBasketLineByIdResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GetBasketLinesByBasketIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketId string `protobuf:"bytes,1,opt,name=basketId,proto3" json:"basketId,omitempty"`
}

func (x *GetBasketLinesByBasketIdRequest) Reset() {
	*x = GetBasketLinesByBasketIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasketLinesByBasketIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketLinesByBasketIdRequest) ProtoMessage() {}

func (x *GetBasketLinesByBasketIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketLinesByBasketIdRequest.ProtoReflect.Descriptor instead.
func (*GetBasketLinesByBasketIdRequest) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{19}
}

func (x *GetBasketLinesByBasketIdRequest) GetBasketId() string {
	if x != nil {
		return x.BasketId
	}
	return ""
}

type GetBasketLinesByBasketIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketLine []*BasketLine `protobuf:"bytes,1,rep,name=basket_line,json=basketLine,proto3" json:"basket_line,omitempty"`
}

func (x *GetBasketLinesByBasketIdResponse) Reset() {
	*x = GetBasketLinesByBasketIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasketLinesByBasketIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketLinesByBasketIdResponse) ProtoMessage() {}

func (x *GetBasketLinesByBasketIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketLinesByBasketIdResponse.ProtoReflect.Descriptor instead.
func (*GetBasketLinesByBasketIdResponse) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{20}
}

func (x *GetBasketLinesByBasketIdResponse) GetBasketLine() []*BasketLine {
	if x != nil {
		return x.BasketLine
	}
	return nil
}

type BasketCheckoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketId       string `protobuf:"bytes,1,opt,name=basket_id,json=basketId,proto3" json:"basket_id,omitempty"`
	FirstName      string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email          string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Address        string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	ZipCode        string `protobuf:"bytes,6,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	City           string `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	Country        string `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	UserId         string `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardNumber     string `protobuf:"bytes,10,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardName       string `protobuf:"bytes,11,opt,name=card_name,json=cardName,proto3" json:"card_name,omitempty"`
	CardExpiration string `protobuf:"bytes,12,opt,name=card_expiration,json=cardExpiration,proto3" json:"card_expiration,omitempty"`
	CvvCode        string `protobuf:"bytes,13,opt,name=cvv_code,json=cvvCode,proto3" json:"cvv_code,omitempty"`
}

func (x *BasketCheckoutRequest) Reset() {
	*x = BasketCheckoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasketCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketCheckoutRequest) ProtoMessage() {}

func (x *BasketCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketCheckoutRequest.ProtoReflect.Descriptor instead.
func (*BasketCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{21}
}

func (x *BasketCheckoutRequest) GetBasketId() string {
	if x != nil {
		return x.BasketId
	}
	return ""
}

func (x *BasketCheckoutRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *BasketCheckoutRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *BasketCheckoutRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BasketCheckoutRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BasketCheckoutRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *BasketCheckoutRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *BasketCheckoutRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *BasketCheckoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BasketCheckoutRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *BasketCheckoutRequest) GetCardName() string {
	if x != nil {
		return x.CardName
	}
	return ""
}

func (x *BasketCheckoutRequest) GetCardExpiration() string {
	if x != nil {
		return x.CardExpiration
	}
	return ""
}

func (x *BasketCheckoutRequest) GetCvvCode() string {
	if x != nil {
		return x.CvvCode
	}
	return ""
}

type BasketCheckoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *BasketCheckoutResponse) Reset() {
	*x = BasketCheckoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ShoppingBasket_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasketCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketCheckoutResponse) ProtoMessage() {}

func (x *BasketCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShoppingBasket_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketCheckoutResponse.ProtoReflect.Descriptor instead.
func (*BasketCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_ShoppingBasket_proto_rawDescGZIP(), []int{22}
}

func (x *BasketCheckoutResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BasketCheckoutResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_ShoppingBasket_proto protoreflect.FileDescriptor

var file_ShoppingBasket_proto_rawDesc = []byte{
	0x0a, 0x14, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x42, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22,
	0x3e, 0x0a, 0x06, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x4d, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x46,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x06,
	0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x22, 0x32, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x62, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x0a, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69,
	0x6e, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x6c, 0x69, 0x6e,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0c, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64,
	0x22, 0x70, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x57, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x0b, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x52,
	0x0a, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0x3e, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x42,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0x78, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69,
	0x6e, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22,
	0x57, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x62,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x0a, 0x62, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0x41, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x1c, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x22, 0x3d, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69,
	0x6e, 0x65, 0x73, 0x42, 0x79, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64,
	0x22, 0x5f, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e,
	0x65, 0x73, 0x42, 0x79, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x6c,
	0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e,
	0x65, 0x22, 0x84, 0x03, 0x0a, 0x15, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x7a, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72,
	0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x72, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63,
	0x61, 0x72, 0x64, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a,
	0x08, 0x63, 0x76, 0x76, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x76, 0x76, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3e, 0x0a, 0x16, 0x42, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x90, 0x0b, 0x0a, 0x0e, 0x53, 0x68, 0x6f,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x12, 0x6e, 0x0a, 0x0b, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x2e, 0x53, 0x68, 0x6f,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23,
	0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22, 0x0b, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x73, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x23, 0x2e, 0x53, 0x68,
	0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x24, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d,
	0x12, 0x8d, 0x01, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x12, 0x23, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x32, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x2c, 0x22, 0x2a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x73, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x7d, 0x2f, 0x7b, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x7d,
	0x12, 0x85, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x12, 0x24, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68,
	0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x73, 0x2f, 0x7b, 0x62,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x7d, 0x12, 0x91, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x27, 0x2e,
	0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24, 0x22, 0x1f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x73, 0x2f, 0x7b,
	0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x7d, 0x3a, 0x01, 0x2a, 0x12, 0x95, 0x01, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x42, 0x79,
	0x49, 0x64, 0x12, 0x28, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e,
	0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x53,
	0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x25, 0x12,
	0x23, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x62, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x73, 0x2f, 0x7b, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e,
	0x65, 0x49, 0x64, 0x7d, 0x12, 0x95, 0x01, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x27, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x28, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2e, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x28, 0x1a, 0x23, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x73, 0x2f, 0x7b, 0x62, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x7d, 0x3a, 0x01, 0x2a, 0x12, 0x9e, 0x01, 0x0a,
	0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e,
	0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x2b, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x4c, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x25, 0x2a, 0x23, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x73, 0x2f, 0x7b,
	0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x7d, 0x12, 0xa6, 0x01,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x73,
	0x42, 0x79, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x2f, 0x2e, 0x53, 0x68, 0x6f,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x42, 0x79, 0x42, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x53, 0x68,
	0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x42, 0x79, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x73, 0x2f, 0x7b, 0x62, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x49, 0x64, 0x7d, 0x12, 0x73, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x12, 0x25, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x3a, 0x01, 0x2a, 0x42, 0x18, 0x5a, 0x16, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x42,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ShoppingBasket_proto_rawDescOnce sync.Once
	file_ShoppingBasket_proto_rawDescData = file_ShoppingBasket_proto_rawDesc
)

func file_ShoppingBasket_proto_rawDescGZIP() []byte {
	file_ShoppingBasket_proto_rawDescOnce.Do(func() {
		file_ShoppingBasket_proto_rawDescData = protoimpl.X.CompressGZIP(file_ShoppingBasket_proto_rawDescData)
	})
	return file_ShoppingBasket_proto_rawDescData
}

var file_ShoppingBasket_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_ShoppingBasket_proto_goTypes = []interface{}{
	(*Event)(nil),                            // 0: ShoppingBasket.Event
	(*CreateEventRequest)(nil),               // 1: ShoppingBasket.CreateEventRequest
	(*CreateEventResponse)(nil),              // 2: ShoppingBasket.CreateEventResponse
	(*GetEventByIdRequest)(nil),              // 3: ShoppingBasket.GetEventByIdRequest
	(*GetEventByIdResponse)(nil),             // 4: ShoppingBasket.GetEventByIdResponse
	(*Basket)(nil),                           // 5: ShoppingBasket.Basket
	(*CreateBasketRequest)(nil),              // 6: ShoppingBasket.CreateBasketRequest
	(*CreateBasketResponse)(nil),             // 7: ShoppingBasket.CreateBasketResponse
	(*GetBasketByIdRequest)(nil),             // 8: ShoppingBasket.GetBasketByIdRequest
	(*GetBasketByIdResponse)(nil),            // 9: ShoppingBasket.GetBasketByIdResponse
	(*BasketLine)(nil),                       // 10: ShoppingBasket.BasketLine
	(*CreateBasketLineRequest)(nil),          // 11: ShoppingBasket.CreateBasketLineRequest
	(*CreateBasketLineResponse)(nil),         // 12: ShoppingBasket.CreateBasketLineResponse
	(*GetBasketLineByIdRequest)(nil),         // 13: ShoppingBasket.GetBasketLineByIdRequest
	(*GetBasketLineByIdResponse)(nil),        // 14: ShoppingBasket.GetBasketLineByIdResponse
	(*UpdateBasketLineRequest)(nil),          // 15: ShoppingBasket.UpdateBasketLineRequest
	(*UpdateBasketLineResponse)(nil),         // 16: ShoppingBasket.UpdateBasketLineResponse
	(*DeleteBasketLineByIdRequest)(nil),      // 17: ShoppingBasket.DeleteBasketLineByIdRequest
	(*DeleteBasketLineByIdResponse)(nil),     // 18: ShoppingBasket.DeleteBasketLineByIdResponse
	(*GetBasketLinesByBasketIdRequest)(nil),  // 19: ShoppingBasket.GetBasketLinesByBasketIdRequest
	(*GetBasketLinesByBasketIdResponse)(nil), // 20: ShoppingBasket.GetBasketLinesByBasketIdResponse
	(*BasketCheckoutRequest)(nil),            // 21: ShoppingBasket.BasketCheckoutRequest
	(*BasketCheckoutResponse)(nil),           // 22: ShoppingBasket.BasketCheckoutResponse
}
var file_ShoppingBasket_proto_depIdxs = []int32{
	0,  // 0: ShoppingBasket.CreateEventResponse.event:type_name -> ShoppingBasket.Event
	0,  // 1: ShoppingBasket.GetEventByIdResponse.event:type_name -> ShoppingBasket.Event
	5,  // 2: ShoppingBasket.CreateBasketResponse.basket:type_name -> ShoppingBasket.Basket
	5,  // 3: ShoppingBasket.GetBasketByIdResponse.basket:type_name -> ShoppingBasket.Basket
	10, // 4: ShoppingBasket.CreateBasketLineResponse.basket_line:type_name -> ShoppingBasket.BasketLine
	10, // 5: ShoppingBasket.GetBasketLineByIdResponse.basket_line:type_name -> ShoppingBasket.BasketLine
	10, // 6: ShoppingBasket.UpdateBasketLineResponse.basket_line:type_name -> ShoppingBasket.BasketLine
	10, // 7: ShoppingBasket.GetBasketLinesByBasketIdResponse.basket_line:type_name -> ShoppingBasket.BasketLine
	1,  // 8: ShoppingBasket.ShoppingBasket.CreateEvent:input_type -> ShoppingBasket.CreateEventRequest
	3,  // 9: ShoppingBasket.ShoppingBasket.GetEventById:input_type -> ShoppingBasket.GetEventByIdRequest
	6,  // 10: ShoppingBasket.ShoppingBasket.CreateBasket:input_type -> ShoppingBasket.CreateBasketRequest
	8,  // 11: ShoppingBasket.ShoppingBasket.GetBasketById:input_type -> ShoppingBasket.GetBasketByIdRequest
	11, // 12: ShoppingBasket.ShoppingBasket.CreateBasketLine:input_type -> ShoppingBasket.CreateBasketLineRequest
	13, // 13: ShoppingBasket.ShoppingBasket.GetBasketLineById:input_type -> ShoppingBasket.GetBasketLineByIdRequest
	15, // 14: ShoppingBasket.ShoppingBasket.UpdateBasketLine:input_type -> ShoppingBasket.UpdateBasketLineRequest
	17, // 15: ShoppingBasket.ShoppingBasket.DeleteBasketLineById:input_type -> ShoppingBasket.DeleteBasketLineByIdRequest
	19, // 16: ShoppingBasket.ShoppingBasket.GetBasketLinesByBasketId:input_type -> ShoppingBasket.GetBasketLinesByBasketIdRequest
	21, // 17: ShoppingBasket.ShoppingBasket.Checkout:input_type -> ShoppingBasket.BasketCheckoutRequest
	2,  // 18: ShoppingBasket.ShoppingBasket.CreateEvent:output_type -> ShoppingBasket.CreateEventResponse
	4,  // 19: ShoppingBasket.ShoppingBasket.GetEventById:output_type -> ShoppingBasket.GetEventByIdResponse
	7,  // 20: ShoppingBasket.ShoppingBasket.CreateBasket:output_type -> ShoppingBasket.CreateBasketResponse
	9,  // 21: ShoppingBasket.ShoppingBasket.GetBasketById:output_type -> ShoppingBasket.GetBasketByIdResponse
	12, // 22: ShoppingBasket.ShoppingBasket.CreateBasketLine:output_type -> ShoppingBasket.CreateBasketLineResponse
	14, // 23: ShoppingBasket.ShoppingBasket.GetBasketLineById:output_type -> ShoppingBasket.GetBasketLineByIdResponse
	16, // 24: ShoppingBasket.ShoppingBasket.UpdateBasketLine:output_type -> ShoppingBasket.UpdateBasketLineResponse
	18, // 25: ShoppingBasket.ShoppingBasket.DeleteBasketLineById:output_type -> ShoppingBasket.DeleteBasketLineByIdResponse
	20, // 26: ShoppingBasket.ShoppingBasket.GetBasketLinesByBasketId:output_type -> ShoppingBasket.GetBasketLinesByBasketIdResponse
	22, // 27: ShoppingBasket.ShoppingBasket.Checkout:output_type -> ShoppingBasket.BasketCheckoutResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ShoppingBasket_proto_init() }
func file_ShoppingBasket_proto_init() {
	if File_ShoppingBasket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ShoppingBasket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEventByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Basket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBasketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBasketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasketByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasketByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasketLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBasketLineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBasketLineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasketLineByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasketLineByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBasketLineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBasketLineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBasketLineByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBasketLineByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasketLinesByBasketIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasketLinesByBasketIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasketCheckoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ShoppingBasket_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasketCheckoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ShoppingBasket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ShoppingBasket_proto_goTypes,
		DependencyIndexes: file_ShoppingBasket_proto_depIdxs,
		MessageInfos:      file_ShoppingBasket_proto_msgTypes,
	}.Build()
	File_ShoppingBasket_proto = out.File
	file_ShoppingBasket_proto_rawDesc = nil
	file_ShoppingBasket_proto_goTypes = nil
	file_ShoppingBasket_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ShoppingBasketClient is the client API for ShoppingBasket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShoppingBasketClient interface {
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error)
	GetEventById(ctx context.Context, in *GetEventByIdRequest, opts ...grpc.CallOption) (*GetEventByIdResponse, error)
	CreateBasket(ctx context.Context, in *CreateBasketRequest, opts ...grpc.CallOption) (*CreateBasketResponse, error)
	GetBasketById(ctx context.Context, in *GetBasketByIdRequest, opts ...grpc.CallOption) (*GetBasketByIdResponse, error)
	CreateBasketLine(ctx context.Context, in *CreateBasketLineRequest, opts ...grpc.CallOption) (*CreateBasketLineResponse, error)
	GetBasketLineById(ctx context.Context, in *GetBasketLineByIdRequest, opts ...grpc.CallOption) (*GetBasketLineByIdResponse, error)
	UpdateBasketLine(ctx context.Context, in *UpdateBasketLineRequest, opts ...grpc.CallOption) (*UpdateBasketLineResponse, error)
	DeleteBasketLineById(ctx context.Context, in *DeleteBasketLineByIdRequest, opts ...grpc.CallOption) (*DeleteBasketLineByIdResponse, error)
	GetBasketLinesByBasketId(ctx context.Context, in *GetBasketLinesByBasketIdRequest, opts ...grpc.CallOption) (*GetBasketLinesByBasketIdResponse, error)
	Checkout(ctx context.Context, in *BasketCheckoutRequest, opts ...grpc.CallOption) (*BasketCheckoutResponse, error)
}

type shoppingBasketClient struct {
	cc grpc.ClientConnInterface
}

func NewShoppingBasketClient(cc grpc.ClientConnInterface) ShoppingBasketClient {
	return &shoppingBasketClient{cc}
}

func (c *shoppingBasketClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*CreateEventResponse, error) {
	out := new(CreateEventResponse)
	err := c.cc.Invoke(ctx, "/ShoppingBasket.ShoppingBasket/CreateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingBasketClient) GetEventById(ctx context.Context, in *GetEventByIdRequest, opts ...grpc.CallOption) (*GetEventByIdResponse, error) {
	out := new(GetEventByIdResponse)
	err := c.cc.Invoke(ctx, "/ShoppingBasket.ShoppingBasket/GetEventById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingBasketClient) CreateBasket(ctx context.Context, in *CreateBasketRequest, opts ...grpc.CallOption) (*CreateBasketResponse, error) {
	out := new(CreateBasketResponse)
	err := c.cc.Invoke(ctx, "/ShoppingBasket.ShoppingBasket/CreateBasket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingBasketClient) GetBasketById(ctx context.Context, in *GetBasketByIdRequest, opts ...grpc.CallOption) (*GetBasketByIdResponse, error) {
	out := new(GetBasketByIdResponse)
	err := c.cc.Invoke(ctx, "/ShoppingBasket.ShoppingBasket/GetBasketById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingBasketClient) CreateBasketLine(ctx context.Context, in *CreateBasketLineRequest, opts ...grpc.CallOption) (*CreateBasketLineResponse, error) {
	out := new(CreateBasketLineResponse)
	err := c.cc.Invoke(ctx, "/ShoppingBasket.ShoppingBasket/CreateBasketLine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingBasketClient) GetBasketLineById(ctx context.Context, in *GetBasketLineByIdRequest, opts ...grpc.CallOption) (*GetBasketLineByIdResponse, error) {
	out := new(GetBasketLineByIdResponse)
	err := c.cc.Invoke(ctx, "/ShoppingBasket.ShoppingBasket/GetBasketLineById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingBasketClient) UpdateBasketLine(ctx context.Context, in *UpdateBasketLineRequest, opts ...grpc.CallOption) (*UpdateBasketLineResponse, error) {
	out := new(UpdateBasketLineResponse)
	err := c.cc.Invoke(ctx, "/ShoppingBasket.ShoppingBasket/UpdateBasketLine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingBasketClient) DeleteBasketLineById(ctx context.Context, in *DeleteBasketLineByIdRequest, opts ...grpc.CallOption) (*DeleteBasketLineByIdResponse, error) {
	out := new(DeleteBasketLineByIdResponse)
	err := c.cc.Invoke(ctx, "/ShoppingBasket.ShoppingBasket/DeleteBasketLineById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingBasketClient) GetBasketLinesByBasketId(ctx context.Context, in *GetBasketLinesByBasketIdRequest, opts ...grpc.CallOption) (*GetBasketLinesByBasketIdResponse, error) {
	out := new(GetBasketLinesByBasketIdResponse)
	err := c.cc.Invoke(ctx, "/ShoppingBasket.ShoppingBasket/GetBasketLinesByBasketId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingBasketClient) Checkout(ctx context.Context, in *BasketCheckoutRequest, opts ...grpc.CallOption) (*BasketCheckoutResponse, error) {
	out := new(BasketCheckoutResponse)
	err := c.cc.Invoke(ctx, "/ShoppingBasket.ShoppingBasket/Checkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShoppingBasketServer is the server API for ShoppingBasket service.
type ShoppingBasketServer interface {
	CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error)
	GetEventById(context.Context, *GetEventByIdRequest) (*GetEventByIdResponse, error)
	CreateBasket(context.Context, *CreateBasketRequest) (*CreateBasketResponse, error)
	GetBasketById(context.Context, *GetBasketByIdRequest) (*GetBasketByIdResponse, error)
	CreateBasketLine(context.Context, *CreateBasketLineRequest) (*CreateBasketLineResponse, error)
	GetBasketLineById(context.Context, *GetBasketLineByIdRequest) (*GetBasketLineByIdResponse, error)
	UpdateBasketLine(context.Context, *UpdateBasketLineRequest) (*UpdateBasketLineResponse, error)
	DeleteBasketLineById(context.Context, *DeleteBasketLineByIdRequest) (*DeleteBasketLineByIdResponse, error)
	GetBasketLinesByBasketId(context.Context, *GetBasketLinesByBasketIdRequest) (*GetBasketLinesByBasketIdResponse, error)
	Checkout(context.Context, *BasketCheckoutRequest) (*BasketCheckoutResponse, error)
}

// UnimplementedShoppingBasketServer can be embedded to have forward compatible implementations.
type UnimplementedShoppingBasketServer struct {
}

func (*UnimplementedShoppingBasketServer) CreateEvent(context.Context, *CreateEventRequest) (*CreateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEvent not implemented")
}
func (*UnimplementedShoppingBasketServer) GetEventById(context.Context, *GetEventByIdRequest) (*GetEventByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventById not implemented")
}
func (*UnimplementedShoppingBasketServer) CreateBasket(context.Context, *CreateBasketRequest) (*CreateBasketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBasket not implemented")
}
func (*UnimplementedShoppingBasketServer) GetBasketById(context.Context, *GetBasketByIdRequest) (*GetBasketByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBasketById not implemented")
}
func (*UnimplementedShoppingBasketServer) CreateBasketLine(context.Context, *CreateBasketLineRequest) (*CreateBasketLineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBasketLine not implemented")
}
func (*UnimplementedShoppingBasketServer) GetBasketLineById(context.Context, *GetBasketLineByIdRequest) (*GetBasketLineByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBasketLineById not implemented")
}
func (*UnimplementedShoppingBasketServer) UpdateBasketLine(context.Context, *UpdateBasketLineRequest) (*UpdateBasketLineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBasketLine not implemented")
}
func (*UnimplementedShoppingBasketServer) DeleteBasketLineById(context.Context, *DeleteBasketLineByIdRequest) (*DeleteBasketLineByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBasketLineById not implemented")
}
func (*UnimplementedShoppingBasketServer) GetBasketLinesByBasketId(context.Context, *GetBasketLinesByBasketIdRequest) (*GetBasketLinesByBasketIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBasketLinesByBasketId not implemented")
}
func (*UnimplementedShoppingBasketServer) Checkout(context.Context, *BasketCheckoutRequest) (*BasketCheckoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkout not implemented")
}

func RegisterShoppingBasketServer(s *grpc.Server, srv ShoppingBasketServer) {
	s.RegisterService(&_ShoppingBasket_serviceDesc, srv)
}

func _ShoppingBasket_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingBasketServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShoppingBasket.ShoppingBasket/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingBasketServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingBasket_GetEventById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingBasketServer).GetEventById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShoppingBasket.ShoppingBasket/GetEventById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingBasketServer).GetEventById(ctx, req.(*GetEventByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingBasket_CreateBasket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBasketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingBasketServer).CreateBasket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShoppingBasket.ShoppingBasket/CreateBasket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingBasketServer).CreateBasket(ctx, req.(*CreateBasketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingBasket_GetBasketById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBasketByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingBasketServer).GetBasketById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShoppingBasket.ShoppingBasket/GetBasketById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingBasketServer).GetBasketById(ctx, req.(*GetBasketByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingBasket_CreateBasketLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBasketLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingBasketServer).CreateBasketLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShoppingBasket.ShoppingBasket/CreateBasketLine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingBasketServer).CreateBasketLine(ctx, req.(*CreateBasketLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingBasket_GetBasketLineById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBasketLineByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingBasketServer).GetBasketLineById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShoppingBasket.ShoppingBasket/GetBasketLineById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingBasketServer).GetBasketLineById(ctx, req.(*GetBasketLineByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingBasket_UpdateBasketLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBasketLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingBasketServer).UpdateBasketLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShoppingBasket.ShoppingBasket/UpdateBasketLine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingBasketServer).UpdateBasketLine(ctx, req.(*UpdateBasketLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingBasket_DeleteBasketLineById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBasketLineByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingBasketServer).DeleteBasketLineById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShoppingBasket.ShoppingBasket/DeleteBasketLineById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingBasketServer).DeleteBasketLineById(ctx, req.(*DeleteBasketLineByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingBasket_GetBasketLinesByBasketId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBasketLinesByBasketIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingBasketServer).GetBasketLinesByBasketId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShoppingBasket.ShoppingBasket/GetBasketLinesByBasketId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingBasketServer).GetBasketLinesByBasketId(ctx, req.(*GetBasketLinesByBasketIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingBasket_Checkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasketCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingBasketServer).Checkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ShoppingBasket.ShoppingBasket/Checkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingBasketServer).Checkout(ctx, req.(*BasketCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShoppingBasket_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ShoppingBasket.ShoppingBasket",
	HandlerType: (*ShoppingBasketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _ShoppingBasket_CreateEvent_Handler,
		},
		{
			MethodName: "GetEventById",
			Handler:    _ShoppingBasket_GetEventById_Handler,
		},
		{
			MethodName: "CreateBasket",
			Handler:    _ShoppingBasket_CreateBasket_Handler,
		},
		{
			MethodName: "GetBasketById",
			Handler:    _ShoppingBasket_GetBasketById_Handler,
		},
		{
			MethodName: "CreateBasketLine",
			Handler:    _ShoppingBasket_CreateBasketLine_Handler,
		},
		{
			MethodName: "GetBasketLineById",
			Handler:    _ShoppingBasket_GetBasketLineById_Handler,
		},
		{
			MethodName: "UpdateBasketLine",
			Handler:    _ShoppingBasket_UpdateBasketLine_Handler,
		},
		{
			MethodName: "DeleteBasketLineById",
			Handler:    _ShoppingBasket_DeleteBasketLineById_Handler,
		},
		{
			MethodName: "GetBasketLinesByBasketId",
			Handler:    _ShoppingBasket_GetBasketLinesByBasketId_Handler,
		},
		{
			MethodName: "Checkout",
			Handler:    _ShoppingBasket_Checkout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ShoppingBasket.proto",
}
