// Code generated by entc, DO NOT EDIT.

package ent

import (
	"ShoppingBasket/ent/basket"
	"ShoppingBasket/ent/basketline"
	"ShoppingBasket/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BasketUpdate is the builder for updating Basket entities.
type BasketUpdate struct {
	config
	hooks    []Hook
	mutation *BasketMutation
}

// Where appends a list predicates to the BasketUpdate builder.
func (bu *BasketUpdate) Where(ps ...predicate.Basket) *BasketUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetUserId sets the "UserId" field.
func (bu *BasketUpdate) SetUserId(u uuid.UUID) *BasketUpdate {
	bu.mutation.SetUserId(u)
	return bu
}

// AddBasketLineIDs adds the "BasketLine" edge to the BasketLine entity by IDs.
func (bu *BasketUpdate) AddBasketLineIDs(ids ...uuid.UUID) *BasketUpdate {
	bu.mutation.AddBasketLineIDs(ids...)
	return bu
}

// AddBasketLine adds the "BasketLine" edges to the BasketLine entity.
func (bu *BasketUpdate) AddBasketLine(b ...*BasketLine) *BasketUpdate {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return bu.AddBasketLineIDs(ids...)
}

// Mutation returns the BasketMutation object of the builder.
func (bu *BasketUpdate) Mutation() *BasketMutation {
	return bu.mutation
}

// ClearBasketLine clears all "BasketLine" edges to the BasketLine entity.
func (bu *BasketUpdate) ClearBasketLine() *BasketUpdate {
	bu.mutation.ClearBasketLine()
	return bu
}

// RemoveBasketLineIDs removes the "BasketLine" edge to BasketLine entities by IDs.
func (bu *BasketUpdate) RemoveBasketLineIDs(ids ...uuid.UUID) *BasketUpdate {
	bu.mutation.RemoveBasketLineIDs(ids...)
	return bu
}

// RemoveBasketLine removes "BasketLine" edges to BasketLine entities.
func (bu *BasketUpdate) RemoveBasketLine(b ...*BasketLine) *BasketUpdate {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return bu.RemoveBasketLineIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BasketUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bu.hooks) == 0 {
		affected, err = bu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BasketMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bu.mutation = mutation
			affected, err = bu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bu.hooks) - 1; i >= 0; i-- {
			if bu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BasketUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BasketUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BasketUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BasketUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   basket.Table,
			Columns: basket.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: basket.FieldID,
			},
		},
	}
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.UserId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: basket.FieldUserId,
		})
	}
	if bu.mutation.BasketLineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   basket.BasketLineTable,
			Columns: []string{basket.BasketLineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: basketline.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.RemovedBasketLineIDs(); len(nodes) > 0 && !bu.mutation.BasketLineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   basket.BasketLineTable,
			Columns: []string{basket.BasketLineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: basketline.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.BasketLineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   basket.BasketLineTable,
			Columns: []string{basket.BasketLineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: basketline.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{basket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// BasketUpdateOne is the builder for updating a single Basket entity.
type BasketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BasketMutation
}

// SetUserId sets the "UserId" field.
func (buo *BasketUpdateOne) SetUserId(u uuid.UUID) *BasketUpdateOne {
	buo.mutation.SetUserId(u)
	return buo
}

// AddBasketLineIDs adds the "BasketLine" edge to the BasketLine entity by IDs.
func (buo *BasketUpdateOne) AddBasketLineIDs(ids ...uuid.UUID) *BasketUpdateOne {
	buo.mutation.AddBasketLineIDs(ids...)
	return buo
}

// AddBasketLine adds the "BasketLine" edges to the BasketLine entity.
func (buo *BasketUpdateOne) AddBasketLine(b ...*BasketLine) *BasketUpdateOne {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return buo.AddBasketLineIDs(ids...)
}

// Mutation returns the BasketMutation object of the builder.
func (buo *BasketUpdateOne) Mutation() *BasketMutation {
	return buo.mutation
}

// ClearBasketLine clears all "BasketLine" edges to the BasketLine entity.
func (buo *BasketUpdateOne) ClearBasketLine() *BasketUpdateOne {
	buo.mutation.ClearBasketLine()
	return buo
}

// RemoveBasketLineIDs removes the "BasketLine" edge to BasketLine entities by IDs.
func (buo *BasketUpdateOne) RemoveBasketLineIDs(ids ...uuid.UUID) *BasketUpdateOne {
	buo.mutation.RemoveBasketLineIDs(ids...)
	return buo
}

// RemoveBasketLine removes "BasketLine" edges to BasketLine entities.
func (buo *BasketUpdateOne) RemoveBasketLine(b ...*BasketLine) *BasketUpdateOne {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return buo.RemoveBasketLineIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BasketUpdateOne) Select(field string, fields ...string) *BasketUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Basket entity.
func (buo *BasketUpdateOne) Save(ctx context.Context) (*Basket, error) {
	var (
		err  error
		node *Basket
	)
	if len(buo.hooks) == 0 {
		node, err = buo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BasketMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			buo.mutation = mutation
			node, err = buo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(buo.hooks) - 1; i >= 0; i-- {
			if buo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = buo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, buo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BasketUpdateOne) SaveX(ctx context.Context) *Basket {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BasketUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BasketUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BasketUpdateOne) sqlSave(ctx context.Context) (_node *Basket, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   basket.Table,
			Columns: basket.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: basket.FieldID,
			},
		},
	}
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Basket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, basket.FieldID)
		for _, f := range fields {
			if !basket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != basket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.UserId(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: basket.FieldUserId,
		})
	}
	if buo.mutation.BasketLineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   basket.BasketLineTable,
			Columns: []string{basket.BasketLineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: basketline.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.RemovedBasketLineIDs(); len(nodes) > 0 && !buo.mutation.BasketLineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   basket.BasketLineTable,
			Columns: []string{basket.BasketLineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: basketline.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.BasketLineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   basket.BasketLineTable,
			Columns: []string{basket.BasketLineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: basketline.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Basket{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{basket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
