// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: coupon-client/Coupon.proto

package Coupon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coupon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CouponId    string  `protobuf:"bytes,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	Code        string  `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Amount      float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	AlreadyUsed bool    `protobuf:"varint,4,opt,name=already_used,json=alreadyUsed,proto3" json:"already_used,omitempty"`
	ExpireAt    string  `protobuf:"bytes,5,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
}

func (x *Coupon) Reset() {
	*x = Coupon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupon_client_Coupon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coupon) ProtoMessage() {}

func (x *Coupon) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_client_Coupon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coupon.ProtoReflect.Descriptor instead.
func (*Coupon) Descriptor() ([]byte, []int) {
	return file_coupon_client_Coupon_proto_rawDescGZIP(), []int{0}
}

func (x *Coupon) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *Coupon) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Coupon) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Coupon) GetAlreadyUsed() bool {
	if x != nil {
		return x.AlreadyUsed
	}
	return false
}

func (x *Coupon) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

type UseCouponRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CouponCode string `protobuf:"bytes,1,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
}

func (x *UseCouponRequest) Reset() {
	*x = UseCouponRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupon_client_Coupon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponRequest) ProtoMessage() {}

func (x *UseCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_client_Coupon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponRequest.ProtoReflect.Descriptor instead.
func (*UseCouponRequest) Descriptor() ([]byte, []int) {
	return file_coupon_client_Coupon_proto_rawDescGZIP(), []int{1}
}

func (x *UseCouponRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

type UseCouponResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Used int32 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
}

func (x *UseCouponResponse) Reset() {
	*x = UseCouponResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupon_client_Coupon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponResponse) ProtoMessage() {}

func (x *UseCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_client_Coupon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponResponse.ProtoReflect.Descriptor instead.
func (*UseCouponResponse) Descriptor() ([]byte, []int) {
	return file_coupon_client_Coupon_proto_rawDescGZIP(), []int{2}
}

func (x *UseCouponResponse) GetUsed() int32 {
	if x != nil {
		return x.Used
	}
	return 0
}

type GetCouponByCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CouponCode string `protobuf:"bytes,1,opt,name=couponCode,proto3" json:"couponCode,omitempty"`
}

func (x *GetCouponByCodeRequest) Reset() {
	*x = GetCouponByCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupon_client_Coupon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCouponByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCouponByCodeRequest) ProtoMessage() {}

func (x *GetCouponByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_client_Coupon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCouponByCodeRequest.ProtoReflect.Descriptor instead.
func (*GetCouponByCodeRequest) Descriptor() ([]byte, []int) {
	return file_coupon_client_Coupon_proto_rawDescGZIP(), []int{3}
}

func (x *GetCouponByCodeRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

type GetCouponByCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coupon *Coupon `protobuf:"bytes,1,opt,name=coupon,proto3" json:"coupon,omitempty"`
}

func (x *GetCouponByCodeResponse) Reset() {
	*x = GetCouponByCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coupon_client_Coupon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCouponByCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCouponByCodeResponse) ProtoMessage() {}

func (x *GetCouponByCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_client_Coupon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCouponByCodeResponse.ProtoReflect.Descriptor instead.
func (*GetCouponByCodeResponse) Descriptor() ([]byte, []int) {
	return file_coupon_client_Coupon_proto_rawDescGZIP(), []int{4}
}

func (x *GetCouponByCodeResponse) GetCoupon() *Coupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

var File_coupon_client_Coupon_proto protoreflect.FileDescriptor

var file_coupon_client_Coupon_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f,
	0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x43, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x22, 0x91, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6c, 0x72, 0x65,
	0x61, 0x64, 0x79, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x61, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x55, 0x73, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x22, 0x33, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x43,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x32, 0x0a,
	0x11, 0x55, 0x73, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x64, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x38, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x42, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x41, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e,
	0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x32, 0xa9,
	0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x42, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x12, 0x18, 0x2e,
	0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x2e, 0x55, 0x73, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x2e, 0x2f,
	0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x3b, 0x43, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_coupon_client_Coupon_proto_rawDescOnce sync.Once
	file_coupon_client_Coupon_proto_rawDescData = file_coupon_client_Coupon_proto_rawDesc
)

func file_coupon_client_Coupon_proto_rawDescGZIP() []byte {
	file_coupon_client_Coupon_proto_rawDescOnce.Do(func() {
		file_coupon_client_Coupon_proto_rawDescData = protoimpl.X.CompressGZIP(file_coupon_client_Coupon_proto_rawDescData)
	})
	return file_coupon_client_Coupon_proto_rawDescData
}

var file_coupon_client_Coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_coupon_client_Coupon_proto_goTypes = []interface{}{
	(*Coupon)(nil),                  // 0: Coupon.Coupon
	(*UseCouponRequest)(nil),        // 1: Coupon.UseCouponRequest
	(*UseCouponResponse)(nil),       // 2: Coupon.UseCouponResponse
	(*GetCouponByCodeRequest)(nil),  // 3: Coupon.GetCouponByCodeRequest
	(*GetCouponByCodeResponse)(nil), // 4: Coupon.GetCouponByCodeResponse
}
var file_coupon_client_Coupon_proto_depIdxs = []int32{
	0, // 0: Coupon.GetCouponByCodeResponse.coupon:type_name -> Coupon.Coupon
	1, // 1: Coupon.CouponService.UseCoupon:input_type -> Coupon.UseCouponRequest
	3, // 2: Coupon.CouponService.GetCouponByCode:input_type -> Coupon.GetCouponByCodeRequest
	2, // 3: Coupon.CouponService.UseCoupon:output_type -> Coupon.UseCouponResponse
	4, // 4: Coupon.CouponService.GetCouponByCode:output_type -> Coupon.GetCouponByCodeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coupon_client_Coupon_proto_init() }
func file_coupon_client_Coupon_proto_init() {
	if File_coupon_client_Coupon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coupon_client_Coupon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coupon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupon_client_Coupon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseCouponRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupon_client_Coupon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseCouponResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupon_client_Coupon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCouponByCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coupon_client_Coupon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCouponByCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coupon_client_Coupon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coupon_client_Coupon_proto_goTypes,
		DependencyIndexes: file_coupon_client_Coupon_proto_depIdxs,
		MessageInfos:      file_coupon_client_Coupon_proto_msgTypes,
	}.Build()
	File_coupon_client_Coupon_proto = out.File
	file_coupon_client_Coupon_proto_rawDesc = nil
	file_coupon_client_Coupon_proto_goTypes = nil
	file_coupon_client_Coupon_proto_depIdxs = nil
}
