// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	ent "ShoppingBasket/ent"
	context "context"

	entgo_ioent "entgo.io/ent"

	mock "github.com/stretchr/testify/mock"
)

// BasketLineFunc is an autogenerated mock type for the BasketLineFunc type
type BasketLineFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *BasketLineFunc) Execute(_a0 context.Context, _a1 *ent.BasketLineMutation) (entgo_ioent.Value, error) {
	ret := _m.Called(_a0, _a1)

	var r0 entgo_ioent.Value
	if rf, ok := ret.Get(0).(func(context.Context, *ent.BasketLineMutation) entgo_ioent.Value); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entgo_ioent.Value)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *ent.BasketLineMutation) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
