// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"ShoppingBasket/external"
	"ShoppingBasket/handler"
	"ShoppingBasket/repository"
)

// Injectors from wire.go:

func DependencyProvider() (*handler.ShoppingBasket, error) {
	host, err := external.HostProvider()
	if err != nil {
		return nil, err
	}
	client, err := repository.ClientProvider(host)
	if err != nil {
		return nil, err
	}
	basketRepository, err := repository.BasketRepositoryProvider(client)
	if err != nil {
		return nil, err
	}
	basketLineRepository, err := repository.BasketLineRepositoryProvider(client)
	if err != nil {
		return nil, err
	}
	eventRepository, err := repository.EventRepositoryProvider(client)
	if err != nil {
		return nil, err
	}
	shoppingBasket, err := handler.NewShoppingBasketHandler(basketRepository, basketLineRepository, eventRepository)
	if err != nil {
		return nil, err
	}
	return shoppingBasket, nil
}
