// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	Coupon "ShoppingBasket/coupon-client"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CouponServiceHandler is an autogenerated mock type for the CouponServiceHandler type
type CouponServiceHandler struct {
	mock.Mock
}

// UseCoupon provides a mock function with given fields: _a0, _a1, _a2
func (_m *CouponServiceHandler) UseCoupon(_a0 context.Context, _a1 *Coupon.UseCouponRequest, _a2 *Coupon.UseCouponResponse) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Coupon.UseCouponRequest, *Coupon.UseCouponResponse) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
