// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	Coupon "ShoppingBasket/coupon-client"

	client "go-micro.dev/v4/client"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CouponService is an autogenerated mock type for the CouponService type
type CouponService struct {
	mock.Mock
}

// UseCoupon provides a mock function with given fields: ctx, in, opts
func (_m *CouponService) UseCoupon(ctx context.Context, in *Coupon.UseCouponRequest, opts ...client.CallOption) (*Coupon.UseCouponResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *Coupon.UseCouponResponse
	if rf, ok := ret.Get(0).(func(context.Context, *Coupon.UseCouponRequest, ...client.CallOption) *Coupon.UseCouponResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Coupon.UseCouponResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *Coupon.UseCouponRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
