// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	sql "entgo.io/ent/dialect/sql"
	mock "github.com/stretchr/testify/mock"
)

// AggregateFunc is an autogenerated mock type for the AggregateFunc type
type AggregateFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *AggregateFunc) Execute(_a0 *sql.Selector) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(*sql.Selector) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
