// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	ent "ShoppingBasket/ent"

	mock "github.com/stretchr/testify/mock"
)

// basketOption is an autogenerated mock type for the basketOption type
type basketOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *basketOption) Execute(_a0 *ent.BasketMutation) {
	_m.Called(_a0)
}
