// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	ent "ShoppingBasket/ent"

	mock "github.com/stretchr/testify/mock"
)

// CommitHook is an autogenerated mock type for the CommitHook type
type CommitHook struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CommitHook) Execute(_a0 ent.Committer) ent.Committer {
	ret := _m.Called(_a0)

	var r0 ent.Committer
	if rf, ok := ret.Get(0).(func(ent.Committer) ent.Committer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ent.Committer)
		}
	}

	return r0
}
