// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	ent "ShoppingBasket/ent"

	mock "github.com/stretchr/testify/mock"
)

// eventOption is an autogenerated mock type for the eventOption type
type eventOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *eventOption) Execute(_a0 *ent.EventMutation) {
	_m.Called(_a0)
}
