// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Basket is the predicate function for basket builders.
type Basket func(*sql.Selector)

// BasketLine is the predicate function for basketline builders.
type BasketLine func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)
